stepback: false
exec_timeout_secs: 1800

## Variables
variables: 
  - &save-artifact
    command: s3.put
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      bucket: mciuploads
      permissions: public-read
      content_type: application/octet-stream

functions:
  'prepare':
    - command: git.get_project
      params:
        directory: src
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e
          echo "Setting up ./compass_env.sh"

          cat <<EOF_BUILD_SH > ./compass_env.sh
          set -e
          export CI=1
          export EVERGREEN=1

          # Make default evergreen expansions accessible to hadron-build
          export EVERGREEN_ASSET_PREFIX="s3://mciuploads/${project}/${revision}";
          export EVERGREEN_AUTHOR="${author}";
          export EVERGREEN_AWS_ACCESS_KEY_ID="${aws_key}";
          export EVERGREEN_AWS_SECRET_ACCESS_KEY="${aws_secret}";
          export EVERGREEN_BRANCH_NAME="${branch_name}";
          export EVERGREEN_BUILD_ID="${build_id}";
          export EVERGREEN_BUILD_VARIANT="${build_variant}";
          export EVERGREEN_EXECUTION="${execution}";
          export EVERGREEN_IS_PATCH=${is_patch};
          export EVERGREEN_PROJECT="${project}";
          export EVERGREEN_REVISION="${revision}";
          export EVERGREEN_TASK_ID="${task_id}";
          export EVERGREEN_TASK_NAME="${task_name}";
          export EVERGREEN_TASK_URL="https://evergreen.mongodb.com/task/${task_id}";
          export EVERGREEN_VERSION_ID="${version_id}";
          export EVERGREEN_WORKDIR="${workdir}";

          # node stuff
          export ARTIFACTS_PATH="$(pwd)/.deps"
          export NPM_CACHE_DIR="$(pwd)/.deps/npm"
          export NPM_TMP_DIR="$(pwd)/.deps/tmp"
          export NPM_AUTH_TOKEN="${compass_npm_token}"

          export NODE_JS_VERSION="8.9.3"

          # OS detection
          if [ -n "$OSTYPE" ]; then
            if [ "$OSTYPE" == "msys" ]; then
                export PLATFORM='win32'
                export IS_WINDOWS=true
            elif [ "$OSTYPE" == "cygwin" ]; then
                export PLATFORM='win32'
                export IS_WINDOWS=true
            fi
          elif [ `uname` == "Darwin" ]; then
              export PLATFORM='darwin'
              export IS_OSX=true
          else
              export PLATFORM='linux'
              export IS_LINUX=true
              if cat /etc/*release | grep ^NAME | grep Red; then
                  export IS_RHEL=true
              elif cat /etc/*release | grep ^NAME | grep Ubuntu; then
                  export IS_UBUNTU=true
              fi
          fi

          if [ -n "$IS_WINDOWS" ]; then
            export PATH="$(pwd)/.deps:$PATH"
            export APPDATA='Z:\'
          else
            export PATH="$(pwd)/.deps/bin:$PATH"
          fi

          EOF_BUILD_SH

          . ./compass_env.sh

          # Make all the dirs
          mkdir -p $ARTIFACTS_PATH
          mkdir -p $NPM_CACHE_DIR
          mkdir -p $NPM_TMP_DIR

    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e
          . ./compass_env.sh

          echo "Configuring npm..."
          cat <<EOT > .npmrc
          devdir=$NPM_CACHE_DIR/.node-gyp
          init-module=$NPM_CACHE_DIR/.npm-init.js
          cache=$NPM_CACHE_DIR
          tmp=$NPM_TMP_DIR
          _authToken=$NPM_AUTH_TOKEN
          EOT
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -ev
          . ./compass_env.sh
          . .evergreen/preinstall.sh

  'install':
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e
          . ./compass_env.sh

          echo "Installing Compass dependencies..."
          npm ci

          if [ -n "$IS_WINDOWS" ]; then
            echo "Fetching signtool -> notary-service hack..."

            curl -fs \
              -o "signtool.exe" \
              --url "https://s3.amazonaws.com/boxes.10gen.com/build/signtool.exe"
            rm -f node_modules/electron-winstaller/vendor/signtool.exe
            chmod +x signtool.exe
          fi
  'save':
    - command: shell.exec
      params:
        script: |
          set -e
          ls -alh
          tar -zcf compass-build.tgz ./src
    - command: s3.put
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: compass-build.tgz
        remote_file: ${project}/${revision}/build.tgz
        bucket: mciuploads
        permissions: private
        content_type: application/octet-stream

  'restore':
    - command: s3.get
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        local_file: compass-build.tgz
        remote_file: ${project}/${revision}/build.tgz
        bucket: mciuploads
        content_type: application/octet-stream
    - command: shell.exec
      params:
        script: |
          set -e
          tar xzf compass-build.tgz --strip-components=1

  'verify':
    command: shell.exec
    params:
      working_dir: src
      script: |
        set -e

        # Load environment variables
        . ./compass_env.sh

        echo "Run static analysis..."
        npm run check;

  'test':
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e

          # Load environment variables
          . ./compass_env.sh

          cat <<EOF_BUILD_SH > ./compass_test.sh
          set -e
          cd $(pwd)

          # Load environment variables
          . ./compass_env.sh
          set -ev
          MONGODB_VERSION=${mongodb_version|stable} npm test -- --${test_suite}
          EOF_BUILD_SH

          if [ -n "$IS_OSX" ]; then
            ssh -v -p 2222 localhost ". ./compass_test.sh"
          else
            export DISPLAY=:99.0
            set -ev
            . .evergreen/pretest.sh

            echo "Running tests..."
            . ./compass_test.sh

            echo "Tests complete! Cleaning up..."

            if [ -n "$IS_LINUX" ]; then
              sh -e /etc/init.d/xvfb stop
            fi
          fi

  # package and published can now be looped by ${compass_distribution} 
  'package':
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e
          # Load environment variables generated by `prepare`
          . ./compass_env.sh

          echo "Synchronizing evergreen environment from Compass build tools..."
          npm run evergreen-expansions ${compass_distribution} 
    - command: expansions.update
      params:
        file: src/expansions.yml
    - command: shell.exec
      params:
        working_dir: src
        script: |
          set -e
          cat <<EOF_BUILD_SH > ./compass_package.sh
          cd $(pwd)

          # Load environment variables
          . ./compass_env.sh

          # Required to sign release assets
          export NOTARY_URL="http://notary-service.build.10gen.cc:5000"
          export NOTARY_AUTH_TOKEN="${signing_auth_token}"
          export NOTARY_SIGNING_KEY="${signing_key_name}"
          export NOTARY_SIGNING_COMMENT="Evergreen project mongodb/compass ${revision} - ${build_variant} - ${branch_name}"

          echo "Creating signed release build..."
          npm run release ${compass_distribution};
          EOF_BUILD_SH

          if [ -n "$IS_OSX" ]; then
            ssh -v -p 2222 localhost ". ./compass_package.sh"
          else
            . ./compass_package.sh
          fi

  'publish':
    command: shell.exec
    params:
      working_dir: src
      script: |
        set -e

        # Load environment variables
        . ./compass_env.sh

        # Required to upload release assets to GitHub
        export GITHUB_TOKEN=${leafybot_github_token}

        # Required to upload release assets to s3 for download center
        export DOWNLOAD_CENTER_AWS_ACCESS_KEY_ID=${aws_key_evergreen_integrations}
        export DOWNLOAD_CENTER_AWS_SECRET_ACCESS_KEY=${aws_secret_evergreen_integrations}

        echo "Uploading release assets to S3 and GitHub if needed..."
        npm run upload ${compass_distribution}

  'save windows artifacts':
    # setup
    - <<: *save-artifact
      params:
        local_file: src/dist/${windows_setup_filename}
        remote_file: ${project}/${revision}/${windows_setup_filename}
    # MSI
    - <<: *save-artifact
      params:
        local_file: src/dist/${windows_msi_filename}
        remote_file: ${project}/${revision}/${windows_msi_filename}
    # ZIP
    - <<: *save-artifact
      params:
        local_file: src/dist/${windows_zip_filename}
        remote_file: ${project}/${revision}/${windows_zip_filename}
        content_type: application/zip
    # RELEASES file
    - <<: *save-artifact
      params:
        local_file: src/dist/RELEASES
        remote_file: ${project}/${revision}/${compass_distribution}-RELEASES
    # nupkg full
    - <<: *save-artifact
      params:
        local_file: src/dist/${windows_nupkg_full_filename}
        remote_file: ${project}/${revision}/${windows_nupkg_full_filename}

  'save osx artifacts':
    # .dmg
    - <<: *save-artifact
      params:
        local_file: src/dist/${osx_dmg_filename}
        remote_file: ${project}/${revision}/${osx_dmg_filename}
        content_type: 'application/x-apple-diskimage'
    # .zip
    - <<: *save-artifact
      params:
        local_file: src/dist/${osx_zip_filename}
        remote_file: ${project}/${revision}/${osx_zip_filename}
        content_type: application/zip

  'save linux artifacts':
    # .deb
    - <<: *save-artifact
      params:
        local_file: src/dist/${linux_deb_filename}
        remote_file: ${project}/${revision}/${linux_deb_filename}
        content_type: 'application/vnd.debian.binary-package'
    # .tar.gz
    - <<: *save-artifact
      params:
        local_file: src/dist/${linux_tar_filename}
        remote_file: ${project}/${revision}/${linux_tar_filename}
        content_type: application/x-gzip

  'save rhel artifacts':
    # .rpm
    - <<: *save-artifact
      params:
        local_file: src/dist/${linux_rpm_filename}
        remote_file: ${project}/${revision}/${linux_rpm_filename}
        content_type: application/x-redhat-package-manager
    # .tar.gz
    - <<: *save-artifact
      params:
        local_file: src/dist/${linux_tar_filename}
        remote_file: ${project}/${revision}/${linux_tar_filename}
        content_type: application/x-gzip

tasks:
  - name: compile-oneshot
    commands: 
      - func: prepare
      - func: install
      - func: test 
        vars:
          test_suite: functional
      - func: package
        vars: 
          compass_distribution: compass
      - func: publish
        vars: 
          compass_distribution: compass
      - func: 'save osx artifacts'
      - func: package
        vars: 
          compass_distribution: compass-community
      - func: publish
        vars: 
          compass_distribution: compass-community
      - func: 'save osx artifacts'
      - func: package
        vars: 
          compass_distribution: compass-isolated
      - func: publish
        vars: 
          compass_distribution: compass-isolated 
      - func: 'save osx artifacts'
      - func: package
        vars: 
          compass_distribution: compass-readonly
      - func: publish
        vars: 
          compass_distribution: compass-readonly       
      - func: 'save osx artifacts'

  - name: compile
    depends_on: []
    commands:
      - func: prepare
      - func: install
      - func: save

  - name: verify
    depends_on: [compile]
    tags: 
      - 'verify'
    commands:
      - func: restore
      - func: verify 

  - name: test-functional
    depends_on: [compile]
    tags: 
      - 'test'
    commands:
      - func: restore
      - func: test 
        vars:
          test_suite: functional

  - name: package-and-publish-compass
    depends_on: [compile]
    commands:
      - func: restore
      - func: package
        vars: 
          compass_distribution: compass
      - func: publish
        vars: 
          compass_distribution: compass
      - func: 'save windows artifacts'
        variants: [windows]
      - func: 'save osx artifacts'
        variants: [macos]
      - func: 'save linux artifacts'
        variants: [ubuntu]   
      - func: 'save rhel artifacts'
        variants: [rhel]

  - name: package-and-publish-compass-community
    depends_on: [compile]
    commands:
      - func: restore
      - func: package
        vars: 
          compass_distribution: compass-community
      - func: publish
        vars: 
          compass_distribution: compass-community
      - func: 'save windows artifacts'
        variants: [windows]
      - func: 'save osx artifacts'
        variants: [macos]
      - func: 'save linux artifacts'
        variants: [ubuntu]   
      - func: 'save rhel artifacts'
        variants: [rhel]

  - name: package-and-publish-compass-isolated
    depends_on: [compile]
    commands:
      - func: restore
      - func: package
        vars: 
          compass_distribution: compass-isolated
      - func: publish
        vars: 
          compass_distribution: compass-isolated
      - func: 'save windows artifacts'
        variants: [windows]
      - func: 'save osx artifacts'
        variants: [macos]
      - func: 'save linux artifacts'
        variants: [ubuntu]   
      - func: 'save rhel artifacts'
        variants: [rhel]

  - name: package-and-publish-compass-readonly
    depends_on: [compile]
    commands:
      - func: restore
      - func: package
        vars: 
          compass_distribution: compass-readonly
      - func: publish
        vars: 
          compass_distribution: compass-readonly
      - func: 'save windows artifacts'
        variants: [windows]
      - func: 'save osx artifacts'
        variants: [macos]
      - func: 'save linux artifacts'
        variants: [ubuntu]   
      - func: 'save rhel artifacts'
        variants: [rhel]
  
  # NOTE (@imlucas) Examples of how to extend which tests run
  # and against which MongoDB Server version.
  # 
  # - name: test-renderer
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: renderer

  # - name: test-main
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: main

  # - name: test-enzyme
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: enzyme

  # - name: test-unit
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: unit
  #         mongodb_version: stable

  # - name: test-functional-unstable-server
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: functional
  #         mongodb_version: unstable

  # - name: test-functional-36x-server
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: functional
  #         mongodb_version: 3.6.x

  # - name: test-functional-34x-server
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: functional
  #         mongodb_version: 3.4.x
  
  # - name: test-functional-26x-server
  #   depends_on: [compile]
  #   tags: 
  #     - 'test'
  #   commands:
  #     - func: restore
  #     - func: test 
  #       vars:
  #         test_suite: functional
  #         mongodb_version: 2.6.x

# TODO (@imlucas) determine OS/version deprecation policy, following server, so we don't fall behind
# what maximal resources we're using.
# See https://docs.google.com/document/d/1IfQGC7wTtrlsc2SqURirvt_4uMuU606nXNbu-stw6bQ/edit
buildvariants:
  - name: macos
    display_name: MacOS
    # TODO (@imlucas) Ideally we'd run tests/fanout builds like the other platforms
    # on `macos-1012` but the setup windowserver" scripting is currently missing on 1012.
    run_on: osx-1010-compass
    tasks:
      - name: compile-oneshot

  - name: windows
    display_name: Windows
    run_on: windows-64-vs2017-test
    expansions:
      compass_distribution: compass
    tasks:
      - name: compile
        run_on: windows-64-vs2017-compile
      - name: verify
      - name: test-functional
      # NOTE (@imlucas) See above for activating more tests
      # - name: test-unit
      # - name: test-main
      # - name: test-renderer
      # - name: test-enzyme    
      # - name: test-functional-unstable-server
      # - name: test-functional-36x-server
      # - name: test-functional-34x-server
      # - name: test-functional-26x-server
      - name: package-and-publish-compass
      - name: package-and-publish-compass-community
      - name: package-and-publish-compass-isolated
      - name: package-and-publish-compass-readonly

  - name: ubuntu
    display_name: Ubuntu
    run_on: ubuntu1404-test
    tasks:
      - name: compile
      - name: verify
      - name: test-functional
      - name: package-and-publish-compass
      - name: package-and-publish-compass-community
      - name: package-and-publish-compass-isolated
      - name: package-and-publish-compass-readonly
  - name: rhel
    display_name: RHEL
    run_on: rhel70
    tasks:
      - name: compile
      - name: verify
      - name: test-functional
      - name: package-and-publish-compass
      - name: package-and-publish-compass-community
      - name: package-and-publish-compass-isolated
      - name: package-and-publish-compass-readonly